version: '3.8'

services:
  client:
    container_name: client
    build: ./client
    depends_on:
      - server
    ports:
      - "8080:8080"
  server:
    container_name: server
    volumes:
      - log:/log
    ports:
      - "8008:8008"
    build: ./server
    depends_on:
      - mongodb
  mongodb:
    container_name: mongo
    image: mongo:6.0.2
    volumes:
      - mongo:/data/db
volumes:
  log:
  mongo: