version: '3.8'

services:
  client:
    container_name: client
    build: ./client
    depends_on:
      - server
    ports:
      - "8070:8070"
  server:
    container_name: server
    volumes:
      - log:/log
    ports:
      - "8008:8008"
    env_file:
      - .env
    build: ./server
    depends_on:
      - mongodb
  mongodb:
    container_name: mongo
    env_file:
      - .env
    image: mongo:6.0.2
    volumes:
      - mongo:/data/db
  mongo-seed:
    env_file:
      - .env
    build: ./database
    depends_on:
      - mongodb
volumes:
  log:
  mongo: